version: "3"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass 25801ec1eacbb3ee69c16761d573e0e6ae03bf3eb15682cee541b4b599de8977
    volumes:
      - redis:/data
    expose:
      - 6379

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db

  api:
    build: .
    command: sh entry-point.sh
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/wellgab
    depends_on:
      - mongodb
      - redis

volumes:
  mongo:
  redis:
    driver: local
