version: "3"
services:
  api:
    build: .
    # depends_on:
    #   mongodb:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy
    depends_on:
      - mongodb
      - redis
    ports: 
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=''
      # - MONGO_INITDB_DATABASE=wellgab
    # healthcheck:
    #   test: ["CMD", "mongo", "--eval", "printjson(db.serverStatus())"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    volumes:
      - mongo:/data/db

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - backend-net
    # healthcheck:
    #   test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
    #   interval: 10s
    #   start_period: 10s
    #   timeout: 4s
    #   retries: 3
    volumes:
      - redis:/root/redis

volumes:
  mongo:
  redis:

networks:
  backend-net:
    driver: bridge
    name: services_net