name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          envkey_REDIS_URL: ${{ secrets.REDIS_URL }}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          envkey_ALGORITHM: ${{ secrets.ALGORITHM }}
          envkey_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          envkey_AUTH0_ALGORITHM: ${{ secrets.AUTH0_ALGORITHM }}
          envkey_API_AUDIENCE: ${{ secrets.API_AUDIENCE }}
          envkey_MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          envkey_MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}

          file_name: .env
          fail_on_empty: false

      - name: Build Docker images
        run: |
          docker compose build --force-rm --no-cache

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: Run Docker images
        run: |
          docker compose up -d --force-recreate --remove-orphans
